apiVersion: v2
name: bitnami-consul
description: Consul from Bitnami

type: application

version: 9.0.3

appVersion: 1.9.0

dependencies:
- name: consul
  repository: https://charts.bitnami.com/bitnami
  version: 9.0.3